### ISSUE TITLE
[MikTeX Portable] Can't add local texmf directory

### ISSUE THREAD

**Issue by benplm** [MiKTeX/miktex#66]
I installed latest portable build (2.9.6615-x64) on Windows 10 (user only install), run the update wizard and tried to add my local texmf directory using either MikTeX Console GUI or ` initexmf --register-root=path-to-texmf ` with no results, i.e. the changes in the directory list are not stored and disappear after closing and re-opening MikTeX Console.

Therefore, I'm not able to use my custom packages when compiling.

It worked fine with previous portable build (same custom texmf directory, same PC).

**Comment by edocevoli** [comment]
Thank you. I can reproduce this bug.

A workaround exists:

```
cd \PATH\TO\MIKTEXPORTABLE
copy texmfs\config\miktex\config\miktexstartup.ini texmfs\install\miktex\config\miktexstartup.ini
```

**Comment by benplm** [comment]
Great! Thanks for the workaround!

**Comment by edocevoli** [comment]
Thank you, this has been fixed.

**Comment by Quantasom** [comment]
I've installed Portable Edition 2.9.6621 on Windows 10 Pro (build 16299.371) on a hard disk drive in E:\Essentials\LaTeX-Environment\LaTeX\MiKTeX\. I've still got the problem that I can't add a custom texmf directory permanently. I can add it in the console just fine without any issues and the path shows up in the list as E:/Essentials/LaTeX-Environment/LaTeX/mytexmf), but it's gone as soon as I restart the console. Packages inside the custom texmf path can't be found when compiling a LaTeX document. The file \mytexmf\miktex\data\le\texmf.fndb shows up in the directory, though.

The workaraound doesn't work, because miktexstartup.ini is already in the right place (texmfs\install\miktex\config\miktexstartup.ini).

**Comment by benplm** [comment]
@Quantasom Yeah, it seems not completely fixed for new installations. However, I've got it to work: copy miktexstartup.ini from texmfs\install\miktex\config\ to \texmfs\config\miktex\config\ (i.e. the opposite way compared to the workaround), then try again to add your custom directory and check if there are differences between the two miktexstartup.ini files. After that, try again to apply the workaround (overwriting the updated file that hopefully contains your custom directory to the original file).

**Comment by Quantasom** [comment]
@benplm Thank you! It worked.

**Comment by georgerbr** [comment]
This issue persists for me, even though I have a fully updated installation:

![miktexportableconsole](https://user-images.githubusercontent.com/4930759/41599638-2d240d94-73aa-11e8-8840-ad01cb4a9a03.png)

I installed miktex-portable-2.9.6621.exe and added my local directories - as soon as I closed the console and opened it again, the directory entries would be lost. I had to find and install an old copy of `miktexstartup.ini` for my local directories to work:

```
;;; MiKTeX startup configuration


[Auto]
Config=Portable

[Paths]

;; ..\..\..\..\texmf;..\..\..\..\texmf-paid
UserRoots=
UserRoots;=..\..\..\..\texmf
UserRoots;=..\..\..\..\texmf-paid
```

**Comment by edocevoli** [comment]
This has been fixed. Please get the latest updates. `miktexstartup.ini` is now written to the correct directory location.

**Comment by a59** [comment]
I tries @benplm suggestion, but there are no differences between the two files.
